### ISSUE TITLE
Inserttags werden ignoriert

### ISSUE THREAD

**Issue by denniserdmann** [dennis-sagasser/contao-room-reservation#3]
Moin Dennis,

ich habe deine Extension gerade mal getestet und auf den ersten Blick macht sie einen guten Eindruck. Allerdings werden bei mir die Inserttags in der E-Mail komplett ignoriert. Ich nutze Contao 3.4.5.

Hast du eine Idee, woran es liegen könnte?

Grüße aus Kiel,
Dennis

**Comment by dennis-sagasser** [comment]
Hi Dennis,

ich habe das Ganze (noch) nicht für Contao-Versionen über 3.2 getestet, aber eigentlich sollte das Ersetzen der Inserttags funktionieren. Hast du es mal mit dem Feld für reinen Text-Inhalt versucht? Kopiere den Text dort rein und setze den Haken bei "Als Text senden". Soweit ich weiß, gibt es ab Contao 3.3 einen neuen TinyMCE. Vielleicht hat es ja etwas damit zu tun.

Gruß
Dennis

**Comment by dennis-sagasser** [comment]
Bei zukünftigen Neuinstallationen sollte es nun klappen. Es hatten sich ein paar Fehler im Default-Text für die Einstellungen eingeschlichen, wodurch das Ersetzen nicht korrekt funktioniert hat. Danke Dennis für den Hinweis ;-). Bei der Gelegenheit habe ich gleich mal die Freigaben aktualisiert...
